// Generated by LiveScript 1.2.0
(function(){
  var SublimeScroll, _sublime_scroll_object;
  SublimeScroll = (function(){
    SublimeScroll.displayName = 'SublimeScroll';
    var prototype = SublimeScroll.prototype, constructor = SublimeScroll;
    prototype.el = {
      wrapper: null,
      iframe: null,
      scroll_bar: null,
      overlay: null
    };
    prototype.dragActive = false;
    prototype.scaleFactor = null;
    prototype.wrapperHeight = null;
    prototype.viewportHeight = null;
    prototype.settings = null;
    prototype.update = function(options){
      return this.settings = $.extend(this.settings, options);
    };
    prototype._get_setting = function(setting){
      if (typeof this.settings[setting] === "function") {
        return this.settings[setting].call(this, this.settings);
      } else {
        return this.settings[setting];
      }
    };
    prototype.get_scrollWith = function(){
      return this._get_setting('scrollWidth');
    };
    prototype.get_scrollHeight = function(){
      return this._get_setting('scrollHeight');
    };
    prototype.get_contentWidth = function(){
      return this._get_setting('contentWidth');
    };
    prototype.get_contentHeight = function(){
      return this._get_setting('contentHeight');
    };
    prototype.get_minWidth = function(){
      return this._get_setting('minWidth');
    };
    function SublimeScroll(options){
      var this$ = this;
      this.onDrag = bind$(this, 'onDrag', prototype);
      this.onDragEnd = bind$(this, 'onDragEnd', prototype);
      this.onScroll = bind$(this, 'onScroll', prototype);
      this.onResize = bind$(this, 'onResize', prototype);
      this.onIframeLoad = bind$(this, 'onIframeLoad', prototype);
      console.log('init');
      if (!(top.document === document)) {
        return this;
      }
      this.settings = {
        top: 0,
        bottom: 0,
        fixedElements: '',
        scrollWidth: 150,
        scrollHeight: function(){
          return $(window).height() - this.settings.top - this.settings.bottom;
        },
        contentWidth: function(){
          return $(document).outerWidth(true);
        },
        contentHeight: function(){
          return $(document).outerHeight(true);
        },
        minWidth: function(){
          return this.get_contentWidth();
        }
      };
      this.update(options);
      console.log(this.settings);
      $(window).bind('resize.sublimeScroll', this.onResize).bind('scroll.sublimeScroll', this.onScroll);
      this.render();
      this.el.overlay.on('mousedown.sublimeScroll', function(event){
        event.preventDefault();
        this$.el.overlay.css({
          width: '100%'
        });
        $(window).on('mousemove.sublimeScroll', this$.onDrag).one('mouseup.sublimeScroll', this$.onDragEnd);
        return this$.onDrag(event);
      });
      return this;
    }
    prototype.render = function(){
      var $html;
      this.el.wrapper = $('<div>', {
        id: "sublime-scroll"
      }).css({
        width: this.get_scrollWith(),
        height: this.get_scrollHeight(),
        top: this.settings.top
      }).appendTo($('body'));
      this.el.iframe = $('<iframe>', {
        id: 'sublime-scroll-iframe',
        frameBorder: '0',
        scrolling: 'no',
        allowTransparency: true
      }).appendTo(this.el.wrapper);
      this.iframe_document = this.el.iframe[0].contentDocument || this.el.iframe.contentWindow.document;
      this.el.scroll_bar = $('<div>', {
        id: 'sublime-scroll-bar'
      });
      $html = $('html').clone();
      $html.find('body').addClass('sublime-scroll-window');
      $html.find('#sublime-scroll').remove();
      this.el.scroll_bar.appendTo($html.find('body'));
      $html.find(this.settings.fixedElements).remove().addClass('sublime-scroll-fixed-element').appendTo(this.el.scroll_ar);
      this.el.iframe.on('load', this.onIframeLoad);
      this.iframe_document.write($html.html());
      this.iframe_document.close();
      return this.el.overlay = $('<div>', {
        id: 'sublime-scroll-overlay'
      }).css({
        top: this.settings.top,
        width: this.get_scrollWith()
      }).appendTo(this.el.wrapper);
    };
    prototype.onIframeLoad = function(event){
      this.el.scroll_bar = $('#sublime-scroll-bar', this.iframe_document);
      $(window).resize().scroll();
      return this.el.wrapper.animate({
        opacity: 1
      }, 100);
    };
    prototype.onResize = function(event){
      var contentWidth, contentHeight;
      contentWidth = this.get_contentWidth();
      contentHeight = this.get_contentHeight();
      if ($(window).width() > this.get_minWidth()) {
        this.el.wrapper.show();
      } else {
        this.el.wrapper.hide();
      }
      this.scaleFactor = this.get_scrollWith() / contentWidth;
      this.contentWidth_scaled = contentWidth * this.scaleFactor;
      this.contentHeight_scaled = contentHeight * this.scaleFactor;
      this.el.iframe.css({
        width: contentWidth,
        height: contentHeight,
        transform: 'scale(' + this.scaleFactor + ')',
        marginLeft: -(contentWidth / 2 - this.contentWidth_scaled / 2),
        marginTop: -(contentHeight / 2 - this.contentHeight_scaled / 2)
      });
      this.wrapperHeight = this.get_scrollHeight();
      this.el.wrapper.css({
        height: this.wrapperHeight
      });
      this.viewportHeight = $(window).height();
      this.viewportHeight_scaled = this.viewportHeight * this.scaleFactor;
      this.el.scroll_bar.css({
        height: this.viewportHeight
      });
      return $(window).scroll();
    };
    prototype.onScroll = function(event){
      var y, ch, max_margin, factor, viewportFactor, margin;
      if (!this.dragActive) {
        this.el.scroll_bar.css({
          top: $(window).scrollTop()
        });
      }
      if (this.contentHeight_scaled > this.wrapperHeight) {
        y = this.el.scroll_bar.position().top * this.scaleFactor;
        ch = this.contentHeight_scaled - this.viewportHeight_scaled;
        max_margin = ch - this.wrapperHeight;
        factor = y / ch;
        viewportFactor = this.viewportHeight_scaled / ch;
        margin = -(factor * max_margin + viewportFactor * y);
      } else {
        margin = 0;
      }
      this.el.iframe.css({
        top: margin
      });
      return this;
    };
    prototype.onDragEnd = function(event){
      event.preventDefault();
      this.el.overlay.css({
        width: this.get_scrollWith()
      });
      $(window).off('mousemove.sublimeScroll', this.onDrag);
      return this.dragActive = false;
    };
    prototype.onDrag = function(event){
      var offsetY, _scaleFactor, y, max_pos;
      this.dragActive = true;
      if (!(event.target === this.el.overlay[0])) {
        return false;
      }
      offsetY = event.offsetY || event.originalEvent.layerY;
      if (this.contentHeight_scaled > this.wrapperHeight) {
        _scaleFactor = this.wrapperHeight / this.get_contentHeight();
      } else {
        _scaleFactor = this.scaleFactor;
      }
      y = offsetY / _scaleFactor - this.viewportHeight / 2;
      max_pos = this.get_contentHeight() - this.viewportHeight;
      if (y < 0) {
        y = 0;
      }
      if (y > max_pos) {
        y = max_pos;
      }
      this.el.scroll_bar.css({
        top: y
      });
      return $(window).scrollTop(y);
    };
    prototype.destroy = function(){
      var _sublime_scroll_object;
      $(window).off('resize.sublimeScroll', this.onResize).off('scroll.sublimeScroll', this.onScroll);
      _sublime_scroll_object = null;
      return this;
    };
    return SublimeScroll;
  }());
  window.SublimeScroll = SublimeScroll;
  _sublime_scroll_object = null;
  $.sublimeScroll = function(options){
    var _sublime_scroll_object;
    if (_sublime_scroll_object && options) {
      return _sublime_scroll_object.update(options);
    } else if (_sublime_scroll_object) {
      return _sublime_scroll_object;
    } else {
      _sublime_scroll_object = new SublimeScroll(options);
      return _sublime_scroll_object;
    }
  };
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
}).call(this);
