// Generated by CoffeeScript 1.3.3

(function($) {
  return $.sublimeScroll = function(options) {
    var $html, $iframe, $scroll_bar, $scroll_overlay, $scroll_wrapper, drag_active, get_content_height, get_content_width, get_height, iframe_document, onDrag, onDragEnd, scale_factor, scroll_bar_height, settings, _get_setting;
    if (!(window.top === window)) {
      return this;
    }
    settings = {
      top: 0,
      bottom: 0,
      zIndex: 200,
      width: 150,
      height: function(settings, $scroll_wrapper) {
        return $(window).height() - settings.top - settings.bottom;
      },
      opacity: 0.9,
      color: 'rgba(255, 255, 255, 0.1)',
      transparent: true,
      fixed_elements: '',
      content_width: function(settings, $scroll_wrapper) {
        return $('body').width();
      },
      content_height: function(settings, $scroll_wrapper) {
        return $('body').outerHeight(true);
      },
      onResize: function(settings, $scroll_wrapper) {
        return true;
      }
    };
    settings = $.extend(settings, options);
    _get_setting = function(setting) {
      if (typeof settings[setting] === "function") {
        return settings[setting](settings, $scroll_wrapper);
      } else {
        return settings[setting];
      }
    };
    get_height = function() {
      return _get_setting('height');
    };
    get_content_width = function() {
      return _get_setting('content_width');
    };
    get_content_height = function() {
      return _get_setting('content_height');
    };
    $scroll_wrapper = $('<div>', {
      id: "sublime-scroll"
    }).css({
      position: 'fixed',
      zIndex: settings.zIndex,
      width: settings.width,
      height: get_height(),
      top: settings.top,
      right: 0,
      overflow: 'hidden',
      opacity: 0
    }).appendTo($('body'));
    $iframe = $('<iframe>', {
      id: 'sublime-scroll-iframe',
      frameBorder: '0',
      scrolling: 'no',
      allowTransparency: true
    }).css({
      position: 'absolute',
      border: 0,
      margin: 0,
      padding: 0,
      overflow: 'hidden',
      top: 0,
      left: 0,
      zIndex: settings.zIndex + 1
    }).appendTo($scroll_wrapper);
    iframe_document = $iframe[0].contentDocument || $iframe.contentWindow.document;
    drag_active = false;
    scale_factor = null;
    scroll_bar_height = null;
    $scroll_bar = $('<div>', {
      id: 'sublime-scroll-bar'
    }).css({
      position: 'absolute',
      right: 0,
      width: '100%',
      backgroundColor: settings.color,
      opacity: settings.opacity,
      zIndex: 99999
    });
    $html = $('html').clone();
    $html.find('body').addClass('sublime-scroll-window');
    $html.find('#sublime-scroll').remove();
    $scroll_bar.appendTo($html.find('body'));
    if (settings.transparent) {
      $html.find('body').css({
        backgroundColor: 'transparent'
      });
    }
    $html.find(settings.fixed_elements).remove().css({
      position: 'absolute'
    }).appendTo($scroll_bar);
    $iframe.load(function() {
      $scroll_bar = $('#sublime-scroll-bar', iframe_document);
      $(window).resize().scroll();
      return $scroll_wrapper.animate({
        opacity: 1
      }, 100);
    });
    iframe_document.write($html.html());
    iframe_document.close();
    $scroll_overlay = $('<div>', {
      id: 'sublime-scroll-overlay'
    }).css({
      position: 'fixed',
      top: settings.top,
      right: 0,
      width: settings.width,
      height: '100%',
      zIndex: settings.zIndex + 3
    }).appendTo($scroll_wrapper);
    onDragEnd = function(event) {
      event.preventDefault();
      $scroll_overlay.css({
        width: settings.width
      });
      $(window).off('mousemove.sublimeScroll', onDrag);
      return drag_active = false;
    };
    onDrag = function(event) {
      var max_pos, offsetY, y;
      drag_active = true;
      if (!(event.target === $scroll_overlay[0])) {
        return false;
      }
      offsetY = event.offsetY || event.originalEvent.layerY;
      y = offsetY / scale_factor - scroll_bar_height / 2;
      max_pos = Math.round(get_content_height() - scroll_bar_height);
      if (y < 0) {
        y = 0;
      }
      if (y > max_pos) {
        y = max_pos;
      }
      $scroll_bar.css({
        top: y
      });
      return $(window).scrollTop(y);
    };
    $scroll_overlay.on('mousedown', function(event) {
      event.preventDefault();
      $scroll_overlay.css({
        width: '100%'
      });
      $(window).on('mousemove.sublimeScroll', onDrag).one('mouseup', onDragEnd);
      return onDrag(event);
    });
    $(window).bind('resize.sublimeScroll', function() {
      var height, width;
      if (!settings.onResize(settings, $scroll_wrapper)) {
        return false;
      }
      width = get_content_width();
      height = get_content_height();
      scale_factor = settings.width / width;
      $iframe.css({
        width: width,
        height: height,
        transform: 'scale(' + scale_factor + ')',
        marginLeft: -(width / 2 - width * scale_factor / 2),
        marginTop: -(height / 2 - height * scale_factor / 2)
      });
      $scroll_wrapper.css({
        height: get_height()
      });
      scroll_bar_height = $(window).height();
      $scroll_bar.css({
        height: scroll_bar_height
      });
      return $(window).scroll();
    });
    $(window).bind('scroll.sublimeScroll', function() {
      var f, margin, scroll_height, window_height, y;
      if (!drag_active) {
        $scroll_bar.css({
          top: $(window).scrollTop()
        });
      }
      scroll_height = get_content_height() * scale_factor;
      window_height = get_height();
      if (scroll_height > window_height) {
        y = $scroll_bar.position().top * scale_factor;
        f = (scroll_bar_height / scroll_height) * y * scale_factor;
        margin = (y / scroll_height) * (window_height - scroll_height) - f;
      } else {
        margin = 0;
      }
      $iframe.css({
        top: margin
      });
      return $iframe.css({
        top: margin
      });
    });
    return this;
  };
})(jQuery);
